<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Seeder;

class SkillCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->catalog() as $category => $skills) {
            foreach ($skills as [$name, $nameEn, $icon]) {
                Skill::firstOrCreate(
                    ['name' => $name],
                    [
                        'name_en' => $nameEn,
                        'category' => $category,
                        'icon' => $icon,
                        'is_active' => true,
                        'is_ghost' => false,
                    ]
                );
            }
        }
    }

    /**
     * @return array<string, array<int, array{0: string, 1: string, 2: string}>>
     */
    private function catalog(): array
    {
        return [
            'برنامه‌نویسی و فناوری اطلاعات' => [
                ['پایتون', 'Python', 'code'],
                ['جاوا اسکریپت', 'JavaScript', 'code'],
                ['تایپ‌اسکریپت', 'TypeScript', 'code'],
                ['جاوا', 'Java', 'code'],
                ['سی‌شارپ', 'C#', 'code'],
                ['سی‌پلاس‌پلاس', 'C++', 'code'],
                ['پی‌اچ‌پی', 'PHP', 'code'],
                ['گولانگ', 'Go (Golang)', 'code'],
                ['روبی', 'Ruby', 'code'],
                ['سوییفت', 'Swift', 'code'],
                ['کاتلین', 'Kotlin', 'code'],
                ['اس‌کیو‌ال', 'SQL', 'data_object'],
                ['لاراول', 'Laravel', 'integration_instructions'],
                ['ری‌اکت', 'React', 'integration_instructions'],
                ['وی‌یو جی‌اس', 'Vue.js', 'integration_instructions'],
                ['انگیولار', 'Angular', 'integration_instructions'],
                ['نود جی‌اس', 'Node.js', 'integration_instructions'],
                ['جنگو', 'Django', 'integration_instructions'],
                ['اسپرینگ بوت', 'Spring Boot', 'integration_instructions'],
                ['دات‌نت', '.NET', 'integration_instructions'],
                ['اچ‌تی‌ام‌ال و سی‌اس‌اس', 'HTML & CSS', 'code'],
                ['مای‌اس‌کیو‌ال', 'MySQL', 'database'],
                ['پست‌گرس‌کیو‌ال', 'PostgreSQL', 'database'],
                ['مونگو‌دی‌بی', 'MongoDB', 'database'],
                ['ردیس', 'Redis', 'database'],
                ['آمازون وب سرویسز', 'Amazon Web Services (AWS)', 'cloud'],
                ['مایکروسافت آژور', 'Microsoft Azure', 'cloud'],
                ['گوگل کلاود پلتفرم', 'Google Cloud Platform', 'cloud'],
                ['رایانش ابری', 'Cloud Computing', 'cloud'],
                ['داکر', 'Docker', 'hub'],
                ['کوبرنتیز', 'Kubernetes', 'hub'],
                ['یکپارچه‌سازی و استقرار مداوم', 'CI/CD', 'integration_instructions'],
                ['گیت و کنترل نسخه', 'Git & Version Control', 'terminal'],
                ['مدیریت سیستم لینوکس', 'Linux System Administration', 'terminal'],
                ['تحلیل داده', 'Data Analysis', 'monitoring'],
                ['مهندسی داده', 'Data Engineering', 'data_object'],
                ['یادگیری ماشین', 'Machine Learning', 'memory'],
                ['هوش مصنوعی', 'Artificial Intelligence', 'psychology'],
                ['یادگیری عمیق', 'Deep Learning', 'memory'],
                ['کلان‌داده', 'Big Data', 'database'],
                ['تجسم‌سازی داده', 'Data Visualization', 'insights'],
                ['هوش تجاری', 'Business Intelligence', 'assessment'],
                ['امنیت سایبری', 'Cybersecurity', 'security'],
                ['امنیت شبکه', 'Network Security', 'security'],
                ['تست نفوذ', 'Penetration Testing', 'bug_report'],
                ['تست و تضمین کیفیت نرم‌افزار', 'Software Testing & QA', 'bug_report'],
                ['توسعه رابط برنامه‌نویسی (API)', 'API Development', 'api'],
                ['توسعه اپلیکیشن موبایل', 'Mobile App Development', 'developer_board'],
                ['مدیریت سیستم', 'System Administration', 'terminal'],
                ['سواد هوش مصنوعی', 'AI Literacy', 'psychology'],
                ['مهندسی هوش مصنوعی', 'AI Engineering', 'psychology'],
                ['بهره‌گیری از مدل‌های زبانی بزرگ', 'LLM Utilization / Prompt Engineering', 'hub'],
                ['اتوماسیون فرآیندهای کسب‌وکار', 'Business Process Automation', 'bolt'],
            ],

            'مدیریت و رهبری' => [
                ['مدیریت پروژه', 'Project Management', 'business_center'],
                ['متدولوژی چابک', 'Agile Methodology', 'hub'],
                ['اسکرام', 'Scrum', 'hub'],
                ['برنامه‌ریزی استراتژیک', 'Strategic Planning', 'insights'],
                ['استراتژی کسب‌وکار', 'Business Strategy', 'trending_up'],
                ['رهبری', 'Leadership', 'military_tech'],
                ['مدیریت تیم', 'Team Management', 'groups'],
                ['مدیریت تغییر', 'Change Management', 'trending_up'],
                ['مدیریت ریسک', 'Risk Management', 'assessment'],
                ['تصمیم‌گیری', 'Decision Making', 'psychology'],
                ['مذاکره', 'Negotiation', 'handshake'],
                ['مدیریت عملکرد', 'Performance Management', 'assessment'],
                ['مدیریت عملیات', 'Operations Management', 'settings'],
                ['توسعه کسب‌وکار', 'Business Development', 'rocket_launch'],
                ['مدیریت بودجه', 'Budget Management', 'paid'],
                ['مدیریت ذی‌نفعان', 'Stakeholder Management', 'handshake'],
                ['هماهنگی میان‌بخشی', 'Cross-functional Coordination', 'groups'],
                ['مدیریت تأمین‌کنندگان', 'Vendor Management', 'business_center'],
                ['بهبود فرآیند', 'Process Improvement', 'trending_up'],
                ['مدیریت ناب', 'Lean Management', 'settings'],
                ['شش سیگما', 'Six Sigma', 'assessment'],
                ['کارآفرینی', 'Entrepreneurship', 'rocket_launch'],
                ['مدیریت محصول', 'Product Management', 'design_services'],
                ['توسعه سازمانی', 'Organizational Development', 'diversity_3'],
            ],

            'بازاریابی و فروش' => [
                ['بازاریابی دیجیتال', 'Digital Marketing', 'campaign'],
                ['بهینه‌سازی موتور جستجو (سئو)', 'Search Engine Optimization (SEO)', 'trending_up'],
                ['بازاریابی موتور جستجو', 'Search Engine Marketing (SEM)', 'campaign'],
                ['بازاریابی محتوا', 'Content Marketing', 'edit'],
                ['بازاریابی شبکه‌های اجتماعی', 'Social Media Marketing', 'forum'],
                ['بازاریابی ایمیلی', 'Email Marketing', 'campaign'],
                ['استراتژی بازاریابی', 'Marketing Strategy', 'insights'],
                ['مدیریت برند', 'Brand Management', 'star'],
                ['تحقیقات بازار', 'Market Research', 'monitoring'],
                ['گوگل آنالیتیکس', 'Google Analytics', 'monitoring'],
                ['تبلیغات گوگل', 'Google Ads', 'campaign'],
                ['تبلیغات کلیکی', 'Pay-Per-Click Advertising (PPC)', 'campaign'],
                ['اتوماسیون بازاریابی', 'Marketing Automation', 'bolt'],
                ['مدیریت ارتباط با مشتری', 'Customer Relationship Management (CRM)', 'handshake'],
                ['فروش', 'Sales', 'trending_up'],
                ['استراتژی فروش', 'Sales Strategy', 'insights'],
                ['فروش سازمانی', 'B2B Sales', 'business_center'],
                ['فروش خرده‌فروشی', 'Retail Sales', 'paid'],
                ['تولید سرنخ فروش', 'Lead Generation', 'trending_up'],
                ['سیلزفورس', 'Salesforce', 'hub'],
                ['بازاریابی اینفلوئنسری', 'Influencer Marketing', 'campaign'],
                ['روابط عمومی', 'Public Relations', 'forum'],
                ['مدیریت تجارت الکترونیک', 'E-commerce Management', 'business_center'],
                ['جذب مشتری', 'Customer Acquisition', 'trending_up'],
                ['مدیریت حساب مشتری', 'Account Management', 'handshake'],
            ],

            'طراحی و خلاقیت' => [
                ['طراحی رابط و تجربه کاربری', 'UI/UX Design', 'design_services'],
                ['طراحی گرافیک', 'Graphic Design', 'palette'],
                ['طراحی محصول', 'Product Design', 'design_services'],
                ['طراحی وب', 'Web Design', 'design_services'],
                ['فتوشاپ', 'Adobe Photoshop', 'brush'],
                ['ایلاستریتور', 'Adobe Illustrator', 'brush'],
                ['پریمیر پرو', 'Adobe Premiere Pro', 'movie'],
                ['فیگما', 'Figma', 'design_services'],
                ['تدوین ویدیو', 'Video Editing', 'videocam'],
                ['موشن گرافیک', 'Motion Graphics', 'movie'],
                ['عکاسی', 'Photography', 'photo_camera'],
                ['انیمیشن‌سازی', 'Animation', 'movie'],
                ['مدل‌سازی سه‌بعدی', '3D Modeling', 'design_services'],
                ['کپی‌رایتینگ', 'Copywriting', 'edit'],
                ['تولید محتوا', 'Content Creation', 'edit'],
                ['برندسازی', 'Branding', 'star'],
                ['تایپوگرافی', 'Typography', 'edit'],
                ['تصویرسازی', 'Illustration', 'brush'],
                ['طراحی داخلی', 'Interior Design', 'palette'],
                ['طراحی مد و لباس', 'Fashion Design', 'brush'],
                ['طراحی صنعتی', 'Industrial Design', 'design_services'],
                ['استوری‌بوردسازی', 'Storyboarding', 'movie'],
                ['طراحی چاپ', 'Print Design', 'palette'],
                ['مدیریت خلاقیت (آرت دایرکشن)', 'Creative Direction', 'lightbulb'],
            ],

            'مالی و حسابداری' => [
                ['تحلیل مالی', 'Financial Analysis', 'assessment'],
                ['حسابداری', 'Accounting', 'calculate'],
                ['دفترداری', 'Bookkeeping', 'calculate'],
                ['بودجه‌بندی', 'Budgeting', 'paid'],
                ['گزارش‌گیری مالی', 'Financial Reporting', 'assessment'],
                ['مدل‌سازی مالی', 'Financial Modeling', 'calculate'],
                ['تهیه اظهارنامه مالیاتی', 'Tax Preparation', 'account_balance'],
                ['حسابرسی', 'Auditing', 'assessment'],
                ['مدیریت حقوق و دستمزد', 'Payroll Management', 'paid'],
                ['مایکروسافت اکسل', 'Microsoft Excel', 'calculate'],
                ['تحلیل سرمایه‌گذاری', 'Investment Analysis', 'trending_up'],
                ['ارزیابی ریسک مالی', 'Financial Risk Assessment', 'assessment'],
                ['حسابداری بهای تمام‌شده', 'Cost Accounting', 'calculate'],
                ['حساب‌های پرداختنی و دریافتنی', 'Accounts Payable/Receivable', 'paid'],
                ['برنامه‌ریزی مالی', 'Financial Planning', 'insights'],
                ['عملیات بانکی', 'Banking Operations', 'account_balance'],
                ['مدیریت جریان نقدی', 'Cash Flow Management', 'paid'],
                ['مالی شرکتی', 'Corporate Finance', 'account_balance'],
                ['کوییک‌بوکس', 'QuickBooks', 'calculate'],
                ['اس‌ای‌پی', 'SAP', 'hub'],
                ['انطباق مالی', 'Financial Compliance', 'gavel'],
            ],

            'منابع انسانی' => [
                ['استخدام و جذب نیرو', 'Recruiting', 'groups'],
                ['جذب استعداد', 'Talent Acquisition', 'groups'],
                ['فرآیند ورود کارکنان', 'Onboarding', 'handshake'],
                ['روابط کارکنان', 'Employee Relations', 'diversity_3'],
                ['ارزیابی عملکرد کارکنان', 'Performance Appraisal', 'assessment'],
                ['حقوق و مزایا', 'Compensation & Benefits', 'paid'],
                ['آموزش و توسعه کارکنان', 'Training & Development', 'school'],
                ['تدوین سیاست‌های منابع انسانی', 'HR Policy Development', 'gavel'],
                ['رعایت قوانین کار', 'Labor Law Compliance', 'gavel'],
                ['برنامه‌ریزی نیروی انسانی', 'Workforce Planning', 'groups'],
                ['مشارکت کارکنان', 'Employee Engagement', 'diversity_3'],
                ['سیستم‌های اطلاعاتی منابع انسانی', 'HR Information Systems (HRIS)', 'database'],
                ['تنوع و شمول', 'Diversity & Inclusion', 'diversity_3'],
                ['برنامه‌ریزی جانشین‌پروری', 'Succession Planning', 'trending_up'],
                ['فرهنگ سازمانی', 'Organizational Culture', 'groups'],
                ['مصاحبه خروج', 'Exit Interviews', 'forum'],
            ],

            'اداری و دفتری' => [
                ['امور اداری دفتری', 'Office Administration', 'business_center'],
                ['مجموعه مایکروسافت آفیس', 'Microsoft Office Suite', 'edit'],
                ['مایکروسافت ورد', 'Microsoft Word', 'edit'],
                ['مایکروسافت پاورپوینت', 'Microsoft PowerPoint', 'edit'],
                ['ورود اطلاعات', 'Data Entry', 'data_object'],
                ['مدیریت زمان‌بندی و تقویم', 'Scheduling & Calendar Management', 'business_center'],
                ['مدیریت اسناد', 'Document Management', 'menu_book'],
                ['دستیاری اجرایی', 'Executive Assistance', 'support_agent'],
                ['هماهنگی جلسات', 'Meeting Coordination', 'groups'],
                ['بایگانی و نگهداری سوابق', 'Filing & Record Keeping', 'menu_book'],
                ['مدیریت مکاتبات', 'Correspondence Management', 'forum'],
                ['سرعت تایپ', 'Typing Speed', 'edit'],
            ],

            'مهندسی و صنعت' => [
                ['مهندسی مکانیک', 'Mechanical Engineering', 'engineering'],
                ['مهندسی برق', 'Electrical Engineering', 'electrical_services'],
                ['مهندسی عمران', 'Civil Engineering', 'construction'],
                ['مهندسی صنایع', 'Industrial Engineering', 'precision_manufacturing'],
                ['مهندسی شیمی', 'Chemical Engineering', 'science'],
                ['اتوکد', 'AutoCAD', 'design_services'],
                ['سالیدورک', 'SolidWorks', 'design_services'],
                ['عملیات تولید', 'Manufacturing Operations', 'precision_manufacturing'],
                ['کنترل کیفیت', 'Quality Control', 'assessment'],
                ['تضمین کیفیت', 'Quality Assurance', 'assessment'],
                ['تعمیر و نگهداری تجهیزات', 'Equipment Maintenance', 'build'],
                ['لوله‌کشی', 'Plumbing', 'plumbing'],
                ['نصب و راه‌اندازی برق', 'Electrical Installation', 'electrical_services'],
                ['جوشکاری', 'Welding', 'build'],
                ['تأسیسات گرمایش و سرمایش', 'HVAC Systems', 'settings'],
                ['مدیریت پروژه ساخت‌وساز', 'Construction Management', 'construction'],
                ['ماشین‌کاری با دستگاه CNC', 'CNC Machining', 'precision_manufacturing'],
                ['مهندسی فرآیند', 'Process Engineering', 'engineering'],
                ['تولید ناب', 'Lean Manufacturing', 'precision_manufacturing'],
                ['ایمنی، بهداشت و محیط زیست', 'Health, Safety & Environment (HSE)', 'security'],
                ['تعمیرات خودرو', 'Automotive Repair', 'directions_car'],
                ['نقشه‌کشی فنی', 'Technical Drawing', 'design_services'],
                ['رباتیک', 'Robotics', 'precision_manufacturing'],
                ['برنامه‌نویسی PLC', 'PLC Programming', 'developer_board'],
            ],

            'بهداشت و درمان' => [
                ['مراقبت از بیمار', 'Patient Care', 'medical_services'],
                ['پرستاری', 'Nursing', 'medical_services'],
                ['اصطلاحات پزشکی', 'Medical Terminology', 'menu_book'],
                ['مستندسازی بالینی', 'Clinical Documentation', 'menu_book'],
                ['کمک‌های اولیه', 'First Aid', 'medical_services'],
                ['احیای قلبی-ریوی', 'CPR', 'medical_services'],
                ['کنترل عفونت', 'Infection Control', 'biotech'],
                ['کدگذاری و صدور صورتحساب پزشکی', 'Medical Coding & Billing', 'calculate'],
                ['اصول داروشناسی', 'Pharmacology Basics', 'science'],
                ['مدیریت خدمات بهداشتی درمانی', 'Healthcare Administration', 'business_center'],
                ['ایمنی بیمار', 'Patient Safety', 'medical_services'],
                ['پرونده الکترونیک سلامت', 'Electronic Health Records (EHR)', 'database'],
                ['واکنش اورژانسی', 'Emergency Response', 'medical_services'],
                ['بهداشت حرفه‌ای', 'Occupational Health', 'medical_services'],
                ['تکنیک‌های فیزیوتراپی', 'Physical Therapy Techniques', 'medical_services'],
                ['مهارت‌های آزمایشگاه پزشکی', 'Medical Laboratory Skills', 'biotech'],
            ],

            'زبان‌ها' => [
                ['زبان فارسی', 'Persian', 'language'],
                ['زبان انگلیسی', 'English', 'language'],
                ['زبان عربی', 'Arabic', 'language'],
                ['زبان فرانسوی', 'French', 'language'],
                ['زبان آلمانی', 'German', 'language'],
                ['زبان اسپانیایی', 'Spanish', 'language'],
                ['زبان چینی (ماندارین)', 'Chinese (Mandarin)', 'translate'],
                ['زبان روسی', 'Russian', 'language'],
                ['زبان ترکی استانبولی', 'Turkish', 'language'],
                ['زبان ایتالیایی', 'Italian', 'language'],
                ['زبان ژاپنی', 'Japanese', 'language'],
                ['زبان کردی', 'Kurdish', 'language'],
                ['نگارش انگلیسی تجاری', 'Business English Writing', 'edit'],
            ],

            'مهارت‌های فردی' => [
                ['ارتباطات مؤثر', 'Communication', 'forum'],
                ['کار تیمی', 'Teamwork', 'groups'],
                ['حل مسئله', 'Problem Solving', 'psychology'],
                ['تفکر انتقادی', 'Critical Thinking', 'psychology'],
                ['مدیریت زمان', 'Time Management', 'self_improvement'],
                ['انطباق‌پذیری', 'Adaptability', 'self_improvement'],
                ['خلاقیت', 'Creativity', 'lightbulb'],
                ['هوش هیجانی', 'Emotional Intelligence', 'psychology'],
                ['سخنرانی عمومی', 'Public Speaking', 'record_voice_over'],
                ['گوش دادن فعال', 'Active Listening', 'headset_mic'],
                ['حل تعارض', 'Conflict Resolution', 'handshake'],
                ['دقت و ریزبینی', 'Attention to Detail', 'assessment'],
                ['اخلاق کاری', 'Work Ethic', 'military_tech'],
                ['پاسخگویی', 'Accountability', 'gavel'],
                ['تاب‌آوری', 'Resilience', 'self_improvement'],
                ['خودانگیزشی', 'Self-Motivation', 'bolt'],
                ['راهنمایی و منتورینگ', 'Mentoring', 'school'],
                ['مهارت‌های ارائه', 'Presentation Skills', 'record_voice_over'],
                ['شبکه‌سازی حرفه‌ای', 'Networking', 'groups'],
                ['آگاهی میان‌فرهنگی', 'Cultural Awareness', 'diversity_3'],
                ['تفکر نوآورانه', 'Innovative Thinking', 'lightbulb'],
                ['حرفه‌ای‌گری', 'Professionalism', 'workspace_premium'],
                ['همدلی', 'Empathy', 'psychology'],
                ['همکاری مشترک', 'Collaboration', 'groups'],
            ],

            'خدمات مشتری' => [
                ['خدمات مشتری', 'Customer Service', 'support_agent'],
                ['پشتیبانی مشتری', 'Customer Support', 'headset_mic'],
                ['رسیدگی به شکایات', 'Complaint Handling', 'forum'],
                ['عملیات مرکز تماس', 'Call Center Operations', 'headset_mic'],
                ['ایجاد رابطه با مشتری', 'Client Relationship Building', 'handshake'],
                ['حفظ مشتری', 'Customer Retention', 'trending_up'],
                ['پشتیبانی میز کمک', 'Help Desk Support', 'support_agent'],
                ['پشتیبانی چت آنلاین', 'Live Chat Support', 'forum'],
                ['مدیریت رضایت مشتری', 'Customer Satisfaction Management', 'insights'],
            ],

            'لجستیک و زنجیره تأمین' => [
                ['مدیریت زنجیره تأمین', 'Supply Chain Management', 'local_shipping'],
                ['هماهنگی لجستیک', 'Logistics Coordination', 'local_shipping'],
                ['مدیریت موجودی', 'Inventory Management', 'business_center'],
                ['مدیریت انبار', 'Warehouse Management', 'local_shipping'],
                ['تدارکات و خرید', 'Procurement', 'paid'],
                ['مدیریت ناوگان حمل‌ونقل', 'Fleet Management', 'directions_car'],
                ['حمل و نقل و بارگیری', 'Freight & Shipping', 'local_shipping'],
                ['عملیات واردات و صادرات', 'Import & Export Operations', 'flight'],
                ['برنامه‌ریزی تقاضا', 'Demand Planning', 'insights'],
                ['بهینه‌سازی مسیر', 'Route Optimization', 'monitoring'],
                ['مدیریت توزیع', 'Distribution Management', 'local_shipping'],
                ['تأمین از فروشندگان', 'Vendor Sourcing', 'handshake'],
                ['انطباق گمرکی', 'Customs Compliance', 'gavel'],
                ['تکمیل و ارسال سفارش', 'Order Fulfillment', 'local_shipping'],
            ],

            'حقوقی و انطباق' => [
                ['مدیریت قراردادها', 'Contract Management', 'gavel'],
                ['تحقیقات حقوقی', 'Legal Research', 'menu_book'],
                ['انطباق با مقررات', 'Regulatory Compliance', 'gavel'],
                ['آشنایی با حقوق شرکت‌ها', 'Corporate Law Knowledge', 'account_balance'],
                ['مدیریت مالکیت فکری', 'Intellectual Property Management', 'workspace_premium'],
                ['حسابرسی ریسک و انطباق', 'Risk & Compliance Auditing', 'assessment'],
                ['حقوق کار', 'Labor Law', 'gavel'],
                ['انطباق با حریم خصوصی داده', 'Data Privacy Compliance', 'security'],
                ['مذاکره قراردادها', 'Contract Negotiation', 'handshake'],
                ['حاکمیت شرکتی', 'Corporate Governance', 'account_balance'],
                ['پشتیبانی دعاوی حقوقی', 'Litigation Support', 'gavel'],
            ],

            'آموزش و تدریس' => [
                ['طراحی برنامه درسی', 'Curriculum Development', 'menu_book'],
                ['طراحی آموزشی', 'Instructional Design', 'school'],
                ['مدیریت کلاس درس', 'Classroom Management', 'school'],
                ['تدریس', 'Teaching', 'school'],
                ['توسعه آموزش الکترونیکی', 'E-Learning Development', 'auto_stories'],
                ['کوچینگ', 'Coaching', 'self_improvement'],
                ['آموزش سازمانی', 'Corporate Training', 'school'],
                ['ارزیابی دانش‌آموزان', 'Student Assessment', 'assessment'],
                ['فناوری آموزشی', 'Educational Technology', 'developer_board'],
                ['مدیریت آموزش عمومی', 'Public Education Administration', 'business_center'],
            ],
        ];
    }
}
