import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Automatically take control of clients
self.skipWaiting();
clientsClaim();

// Retrieve the manifest from the build process
const manifest = self.__WB_MANIFEST;

// Precache all assets generated by the build
precacheAndRoute(manifest);

// Custom fetch listener for LOGGING purposes.
// This ensures we get the "Serving from cache" message the user requested.
// We intercept requests that match our precached assets.
self.addEventListener('fetch', (event) => {
    // Only intercept GET requests
    if (event.request.method !== 'GET') return;

    const url = new URL(event.request.url);

    // Check if the request is for one of our precached assets
    // The manifest entries usually look like { url: 'assets/foo.js', revision: '...' } or just 'assets/foo.js'
    const isPrecached = manifest.some(entry => {
        const assetUrl = (typeof entry === 'string') ? entry : entry.url;
        return url.pathname.endsWith(assetUrl);
    });

    if (isPrecached) {
        event.respondWith(
            caches.match(event.request).then((response) => {
                if (response) {
                    console.log('⚡ [Service Worker] Serving from cache:', url.pathname);
                    return response;
                }
                // If not in cache (rare), fetch from network
                return fetch(event.request);
            })
        );
    }
    // All other requests (API, HTML) fall through to the network naturally
});

console.log('✅ Service Worker Loaded & Ready');
