import { precacheAndRoute, addPlugins } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Automatically take control of clients
self.skipWaiting();
clientsClaim();

// Retrieve the manifest from the build process
const manifest = self.__WB_MANIFEST;

// Add a custom plugin to log cache hits
addPlugins([
    {
        cachedResponseWillBeUsed: async ({ cachedResponse, request }) => {
            if (cachedResponse) {
                // Log only for our precached assets (files from manifest)
                // This prevents logging every single request if other caches exist
                console.log('⚡ [Service Worker] Serving from cache:', new URL(request.url).pathname);
                return cachedResponse;
            }
        }
    }
]);

// Precache all assets generated by the build
precacheAndRoute(manifest);

console.log('✅ Service Worker Loaded & Ready');
