<?php

use Filament\Support\Colors\Color;

return [
    'danger' => Color::Red,
    'gray' => Color::Zinc,
    'info' => Color::Blue,
    'primary' => [
        50 => 'var(--md-sys-color-primary, #4e5f66)',
        100 => 'var(--md-sys-color-primary, #4e5f66)',
        200 => 'var(--md-sys-color-primary, #4e5f66)',
        300 => 'var(--md-sys-color-primary, #4e5f66)',
        400 => 'var(--md-sys-color-primary, #4e5f66)',
        500 => 'var(--md-sys-color-primary, #4e5f66)',
        600 => 'var(--md-sys-color-primary, #4e5f66)',
        700 => 'var(--md-sys-color-primary, #4e5f66)',
        800 => 'var(--md-sys-color-primary, #4e5f66)',
        900 => 'var(--md-sys-color-primary, #4e5f66)',
        950 => 'var(--md-sys-color-primary, #4e5f66)',
    ],
    'success' => Color::Green,
    'warning' => Color::Amber,
    'secondary' => [
        50 => 'var(--md-sys-color-secondary, #535f70)',
        100 => 'var(--md-sys-color-secondary, #535f70)',
        200 => 'var(--md-sys-color-secondary, #535f70)',
        300 => 'var(--md-sys-color-secondary, #535f70)',
        400 => 'var(--md-sys-color-secondary, #535f70)',
        500 => 'var(--md-sys-color-secondary, #535f70)',
        600 => 'var(--md-sys-color-secondary, #535f70)',
        700 => 'var(--md-sys-color-secondary, #535f70)',
        800 => 'var(--md-sys-color-secondary, #535f70)',
        900 => 'var(--md-sys-color-secondary, #535f70)',
        950 => 'var(--md-sys-color-secondary, #535f70)',
    ],

    'slate' => Color::Slate,
    'gray-palette' => Color::Gray,
    'zinc' => Color::Zinc,
    'neutral' => Color::Neutral,
    'stone' => Color::Stone,

    'mauve' => Color::Mauve,
    'olive' => Color::Olive,
    'mist' => Color::Mist,
    'taupe' => Color::Taupe,

    'red' => Color::Red,
    'orange' => Color::Orange,
    'amber' => Color::Amber,
    'yellow' => Color::Yellow,
    'lime' => Color::Lime,
    'green' => Color::Green,
    'emerald' => Color::Emerald,
    'teal' => Color::Teal,
    'cyan' => Color::Cyan,
    'sky' => Color::Sky,
    'blue' => Color::Blue,
    'indigo' => Color::Indigo,
    'violet' => Color::Violet,
    'purple' => Color::Purple,
    'fuchsia' => Color::Fuchsia,
    'pink' => Color::Pink,
    'rose' => Color::Rose,
];
