<?php

use Filament\Support\Colors\Color;

return [
    'danger' => Color::Red,
    'gray' => Color::Zinc,
    'info' => Color::Blue,
    'primary' => [
        50 => 'color-mix(in srgb, var(--md-sys-color-primary) 5%, white)',
        100 => 'color-mix(in srgb, var(--md-sys-color-primary) 10%, white)',
        200 => 'color-mix(in srgb, var(--md-sys-color-primary) 20%, white)',
        300 => 'color-mix(in srgb, var(--md-sys-color-primary) 30%, white)',
        400 => 'color-mix(in srgb, var(--md-sys-color-primary) 40%, white)',
        500 => 'var(--md-sys-color-primary)',
        600 => 'color-mix(in srgb, var(--md-sys-color-primary) 10%, black)',
        700 => 'color-mix(in srgb, var(--md-sys-color-primary) 20%, black)',
        800 => 'color-mix(in srgb, var(--md-sys-color-primary) 30%, black)',
        900 => 'color-mix(in srgb, var(--md-sys-color-primary) 40%, black)',
        950 => 'color-mix(in srgb, var(--md-sys-color-primary) 50%, black)',
    ],
    'success' => Color::Green,
    'warning' => Color::Amber,
    'secondary' => [
        50 => 'color-mix(in srgb, var(--md-sys-color-secondary) 5%, white)',
        100 => 'color-mix(in srgb, var(--md-sys-color-secondary) 10%, white)',
        200 => 'color-mix(in srgb, var(--md-sys-color-secondary) 20%, white)',
        300 => 'color-mix(in srgb, var(--md-sys-color-secondary) 30%, white)',
        400 => 'color-mix(in srgb, var(--md-sys-color-secondary) 40%, white)',
        500 => 'var(--md-sys-color-secondary)',
        600 => 'color-mix(in srgb, var(--md-sys-color-secondary) 10%, black)',
        700 => 'color-mix(in srgb, var(--md-sys-color-secondary) 20%, black)',
        800 => 'color-mix(in srgb, var(--md-sys-color-secondary) 30%, black)',
        900 => 'color-mix(in srgb, var(--md-sys-color-secondary) 40%, black)',
        950 => 'color-mix(in srgb, var(--md-sys-color-secondary) 50%, black)',
    ],

    'slate' => Color::Slate,
    'gray-palette' => Color::Gray,
    'zinc' => Color::Zinc,
    'neutral' => Color::Neutral,
    'stone' => Color::Stone,

    'mauve' => Color::Mauve,
    'olive' => Color::Olive,
    'mist' => Color::Mist,
    'taupe' => Color::Taupe,

    'red' => Color::Red,
    'orange' => Color::Orange,
    'amber' => Color::Amber,
    'yellow' => Color::Yellow,
    'lime' => Color::Lime,
    'green' => Color::Green,
    'emerald' => Color::Emerald,
    'teal' => Color::Teal,
    'cyan' => Color::Cyan,
    'sky' => Color::Sky,
    'blue' => Color::Blue,
    'indigo' => Color::Indigo,
    'violet' => Color::Violet,
    'purple' => Color::Purple,
    'fuchsia' => Color::Fuchsia,
    'pink' => Color::Pink,
    'rose' => Color::Rose,
];
